import {
  Archive,
  BookOpen,
  FileDiff,
  HeartPulse,
  Inbox,
  KeyRound,
  MessageSquareQuote,
  ScrollText,
  Search,
  Server,
  Scale,
  FolderKanban,
  Users,
  Webhook,
  type LucideIcon,
} from 'lucide-react'

/**
 * The console's navigation, declared rather than written out.
 *
 * Deliberately a module of its own, with no DOM in it:
 * `test/unit/cockpit-navigation.test.ts` imports this table and compares it
 * against `src/http/routes.ts`, and it must be able to do that without a
 * browser. That is the same reason `lib/tokens.ts`, `lib/theme-store.ts` and
 * `lib/scopes.ts` are pure — the pieces the rest of the console reads should
 * not need a window to prove they are right.
 *
 * Each entry states the scope that reveals it and the API paths its page
 * reaches, and both are checked against the things that actually decide them:
 * `ROUTES` for the scope and the path set. A navigation table nobody checks is
 * a comment, and the specific failure it prevents is a console that hides a
 * page the server would have served — or offers one it would refuse.
 *
 * Page agents do not edit this file — they drop a fragment into
 * apps/cockpit/nav-entries/<page>.json (see apps/cockpit/PAGES.md) and the
 * integrator merges it here and into router.tsx.
 */
export interface NavEntry {
  to: string
  label: string
  icon: LucideIcon
  /**
   * The scope `ROUTES` demands for this entry's paths, or `null` where it
   * demands none.
   *
   * `null` is a claim, not an omission: it says every path this page reaches
   * is unauthenticated, and the navigation test checks that against `ROUTES`.
   * A page that quietly dropped its gate would fail rather than silently open.
   *
   * The scope named here is the one that REVEALS the page, which is not always
   * the strictest scope on it: the changes queue is `knowledge:read` on
   * purpose, because seeing what is waiting is not the same right as deciding
   * it. The decision buttons gate themselves in-page with `useCan`.
   */
  scope: string | null
  group: string
  /** Every documented path this page reaches, including through its components. */
  api: readonly string[]
  /** Detail routes match by prefix; the home page must not. */
  exact?: boolean
}

/**
 * The wiki block is THE LOOP, read top to bottom: Inbox → Pages → Changes →
 * Answers → Care. Something arrives, it becomes pages, a human decides them, a
 * reader asks a question, and what the asking exposes gets maintained. An
 * operator who reads the sidebar downwards has read the product.
 *
 * `Changes` deliberately stays visible even though folding the review queue in
 * with the Inbox — which already lists the pending changes beside what arrived
 * — would reach a tidy four entries. It is the one queue whose neglect does
 * real damage: unreviewed proposals accumulate silently, an automatic feeder
 * can outrun a human reviewer by hundreds, and nothing on a hidden queue ever
 * says so. Tidiness is not worth a review backlog nobody sees.
 */
export const NAV: readonly NavEntry[] = [
  {
    to: '/',
    label: 'Home',
    icon: BookOpen,
    scope: 'knowledge:read',
    group: 'home',
    exact: true,
    // `health` rather than `stats/coverage`: the composed read carries the same
    // coverage block AND the two live queues the loop is measured by, so the
    // front page asks once for the numbers it used to guess at.
    api: [
      '/v1/spaces/{space}/stats/knowledge',
      '/v1/spaces/{space}/stats/reviews',
      '/v1/spaces/{space}/stats/ingests',
      '/v1/spaces/{space}/health',
      '/v1/spaces/{space}/proposals',
    ],
  },
  {
    to: '/inbox',
    label: 'Inbox',
    icon: Inbox,
    scope: 'knowledge:read',
    group: 'wiki',
    // Revealed by `knowledge:read` and not by `knowledge:propose`, like the
    // changes queue: watching what arrived is not the same right as adding to
    // it. The drop zone and the forms gate themselves in-page with `useCan`.
    //
    // `/v1/spaces/{space}/proposals` is here because "what arrived" and "what
    // of it still needs a decision" are one question and belong on one page.
    //
    // `/v1/ingests/{id}` is deliberately NOT here: the list carries `phase` and
    // `progress` for every row, so the page never reads a job by id, and a
    // declaration nothing calls is the answer a reviewer gets when they ask
    // what this page touches. The two by-id ACTIONS are here — the parked
    // strip's process/discard buttons are the one place a human un-parks a
    // captured note.
    api: [
      '/v1/spaces/{space}/ingests',
      '/v1/spaces/{space}/ingest',
      '/v1/spaces/{space}/ingest/document',
      '/v1/ingests/{id}/process',
      '/v1/ingests/{id}/discard',
      '/v1/spaces/{space}/proposals',
    ],
  },
  {
    to: '/pages',
    label: 'Pages',
    icon: BookOpen,
    scope: 'knowledge:read',
    group: 'wiki',
    // The editor submits a proposal from this page, which is why the write
    // path is declared here and not under the changes queue: an entry lists
    // what its PAGE reaches, not what its noun belongs to.
    api: [
      '/v1/spaces/{space}/concepts',
      '/v1/spaces/{space}/deleted-concepts',
      '/v1/spaces/{space}/concepts/{slug}',
      '/v1/spaces/{space}/concepts/{slug}/history',
      '/v1/spaces/{space}/concepts/{slug}/neighbors',
      '/v1/spaces/{space}/concepts/{slug}/restore',
      '/v1/spaces/{space}/proposals',
    ],
  },
  {
    to: '/changes',
    label: 'Changes',
    icon: FileDiff,
    scope: 'knowledge:read',
    group: 'wiki',
    api: [
      '/v1/spaces/{space}/proposals',
      '/v1/proposals/{id}',
      '/v1/proposals/{id}/lint',
      '/v1/proposals/{id}/approve',
      '/v1/proposals/{id}/reject',
      '/v1/proposals/{id}/request-changes',
      '/v1/proposals/{id}/split',
    ],
  },
  {
    to: '/answers',
    label: 'Answers',
    icon: MessageSquareQuote,
    scope: 'knowledge:read',
    group: 'wiki',
    // `/v1/ingests/{id}` is here because promotion answers with an ingest job
    // and nothing else: the page polls that job so the operator can follow the
    // link to the change it produced instead of being told to go and look.
    api: ['/v1/spaces/{space}/outputs', '/v1/outputs/{id}', '/v1/outputs/{id}/promote', '/v1/ingests/{id}'],
  },
  {
    to: '/care',
    label: 'Care',
    icon: HeartPulse,
    scope: 'knowledge:read',
    group: 'wiki',
    // `knowledge:read` reveals it, and the schedule controls inside are admin.
    // Same reading as the changes queue: seeing what the wiki needs is not the
    // same right as deciding when a report runs. The outputs list feeds the
    // kept-reports history (kind='health'); reading one whole report happens on
    // the Answers page, which declares the by-id path.
    api: ['/v1/spaces/{space}/health', '/v1/spaces/{space}/schedules', '/v1/spaces/{space}/outputs'],
  },
  {
    to: '/sources',
    label: 'Sources',
    icon: Archive,
    scope: 'knowledge:read',
    group: 'archive',
    // No ingest paths any more: a document ENTERS through the Inbox now, and
    // this page is what the archive holds afterwards.
    api: [
      '/v1/spaces/{space}/sources',
      '/v1/spaces/{space}/sources/{id}',
      '/v1/spaces/{space}/source-streams',
      '/v1/spaces/{space}/source-streams/{external_source_id}',
    ],
  },
  {
    to: '/decisions',
    label: 'Decisions',
    icon: Scale,
    scope: 'knowledge:read',
    group: 'archive',
    api: ['/v1/spaces/{space}/decisions', '/v1/spaces/{space}/decisions/{slug}'],
  },
  {
    to: '/charter',
    // "Guidelines" in the interface, `charter` everywhere a machine reads it —
    // the route, the MCP tools, the table and the doc anchors keep the
    // technical name, because renaming an API breaks contracts for no gain.
    label: 'Guidelines',
    icon: ScrollText,
    scope: 'knowledge:read',
    group: 'archive',
    api: ['/v1/spaces/{space}/charter', '/v1/spaces/{space}/charter/versions'],
  },
  {
    to: '/search',
    label: 'Search',
    icon: Search,
    scope: 'knowledge:read',
    group: 'archive',
    api: ['/v1/spaces/{space}/search', '/v1/spaces/{space}/query'],
  },
  {
    to: '/spaces',
    label: 'Wikis',
    icon: FolderKanban,
    scope: 'knowledge:read',
    group: 'installation',
    api: [
      '/v1/spaces',
      '/v1/spaces/{space}',
      '/v1/spaces/{space}/settings',
      '/v1/spaces/{space}/export',
      '/v1/stats/overview',
    ],
  },
  {
    to: '/api-keys',
    label: 'API keys',
    icon: KeyRound,
    scope: 'admin',
    group: 'installation',
    api: ['/v1/api-keys', '/v1/api-keys/{id}'],
  },
  {
    to: '/identities',
    label: 'People',
    icon: Users,
    scope: 'admin',
    group: 'installation',
    api: ['/v1/identities', '/v1/identities/{provider}/{subject}'],
  },
  {
    to: '/webhooks',
    label: 'Webhooks',
    icon: Webhook,
    scope: 'admin',
    group: 'installation',
    api: ['/v1/spaces/{space}/webhooks', '/v1/spaces/{space}/webhooks/{id}/deliveries'],
  },
  {
    to: '/system',
    label: 'System',
    icon: Server,
    scope: 'knowledge:read',
    group: 'installation',
    // The admin-only cards on this page render the server's own 403 rather
    // than disappearing — a reader should be able to see that the numbers
    // exist and are not theirs, which is a different fact from "no data".
    //
    // The first two paths are the surprising ones: `/ready` and the service
    // descriptor are unauthenticated and outside /v1, so this page can show
    // what the installation IS and whether it is up before it shows a single
    // number a scope could withhold.
    api: [
      '/ready',
      '/.well-known/service-descriptor.json',
      '/v1/spaces/{space}/stats/http',
      '/v1/spaces/{space}/stats/usage',
      '/v1/spaces/{space}/stats/llm',
      '/v1/spaces/{space}/stats/webhooks',
      '/v1/stats/mcp',
      '/v1/installation/knowledge-config',
    ],
  },
]

export interface NavGroup {
  id: string
  label: string
  collapsible: boolean
  startsOpen: boolean
  separated: boolean
}

/**
 * The groups, in the order an operator meets them.
 *
 * The Wiki block is the loop and nothing else: five entries somebody can hold
 * in their head, in the order the work happens. Everything that is a way INTO
 * one of those five rather than a step of the loop — the archive the pages are
 * quoted from, the decision log approving them writes, the guidelines that
 * steer synthesis, the search box — moved into `archive`, which starts CLOSED.
 * Nine open entries is a menu; five is a model.
 *
 * `archive` is collapsible and NOT separated: it is still about the knowledge,
 * just one level in. Installation stays the only separated block, because it is
 * the only one about WikiKit itself rather than about what it holds — and
 * test/unit/cockpit-navigation.test.ts holds that to exactly one block.
 */
export const GROUPS: readonly NavGroup[] = [
  { id: 'home', label: '', collapsible: false, startsOpen: true, separated: false },
  { id: 'wiki', label: 'Wiki', collapsible: true, startsOpen: true, separated: false },
  { id: 'archive', label: 'Archive & control', collapsible: true, startsOpen: false, separated: false },
  { id: 'installation', label: 'Installation', collapsible: true, startsOpen: false, separated: true },
]

/** The nav entry a path belongs to — the longest matching prefix. */
export function entryFor(path: string): NavEntry | undefined {
  let best: NavEntry | undefined
  for (const entry of NAV) {
    const matches = entry.exact ? path === entry.to : path === entry.to || path.startsWith(`${entry.to}/`)
    if (matches && (!best || entry.to.length > best.to.length)) best = entry
  }
  return best
}
