import {
  Archive,
  BookOpen,
  FileDiff,
  KeyRound,
  ScrollText,
  Search,
  Server,
  Scale,
  FolderKanban,
  Users,
  Webhook,
  type LucideIcon,
} from 'lucide-react'

/**
 * The console's navigation, declared rather than written out.
 *
 * Deliberately a module of its own, with no DOM in it:
 * `test/unit/cockpit-navigation.test.ts` imports this table and compares it
 * against `src/http/routes.ts`, and it must be able to do that without a
 * browser. That is the same reason `lib/tokens.ts`, `lib/theme-store.ts` and
 * `lib/scopes.ts` are pure — the pieces the rest of the console reads should
 * not need a window to prove they are right.
 *
 * Each entry states the scope that reveals it and the API paths its page
 * reaches, and both are checked against the things that actually decide them:
 * `ROUTES` for the scope and the path set. A navigation table nobody checks is
 * a comment, and the specific failure it prevents is a console that hides a
 * page the server would have served — or offers one it would refuse.
 *
 * Page agents do not edit this file — they drop a fragment into
 * apps/cockpit/nav-entries/<page>.json (see apps/cockpit/PAGES.md) and the
 * integrator merges it here and into router.tsx.
 */
export interface NavEntry {
  to: string
  label: string
  icon: LucideIcon
  /**
   * The scope `ROUTES` demands for this entry's paths, or `null` where it
   * demands none.
   *
   * `null` is a claim, not an omission: it says every path this page reaches
   * is unauthenticated, and the navigation test checks that against `ROUTES`.
   * A page that quietly dropped its gate would fail rather than silently open.
   *
   * The scope named here is the one that REVEALS the page, which is not always
   * the strictest scope on it: the changes queue is `knowledge:read` on
   * purpose, because seeing what is waiting is not the same right as deciding
   * it. The decision buttons gate themselves in-page with `useCan`.
   */
  scope: string | null
  group: string
  /** Every documented path this page reaches, including through its components. */
  api: readonly string[]
  /** Detail routes match by prefix; the home page must not. */
  exact?: boolean
}

export const NAV: readonly NavEntry[] = [
  {
    to: '/',
    label: 'Home',
    icon: BookOpen,
    scope: 'knowledge:read',
    group: 'home',
    exact: true,
    api: [
      '/v1/spaces/{space}/stats/knowledge',
      '/v1/spaces/{space}/stats/reviews',
      '/v1/spaces/{space}/stats/ingests',
      '/v1/spaces/{space}/stats/coverage',
      '/v1/spaces/{space}/proposals',
    ],
  },
  {
    to: '/pages',
    label: 'Pages',
    icon: BookOpen,
    scope: 'knowledge:read',
    group: 'wiki',
    // The editor submits a proposal from this page, which is why the write
    // path is declared here and not under the changes queue: an entry lists
    // what its PAGE reaches, not what its noun belongs to.
    api: [
      '/v1/spaces/{space}/concepts',
      '/v1/spaces/{space}/concepts/{slug}',
      '/v1/spaces/{space}/concepts/{slug}/history',
      '/v1/spaces/{space}/proposals',
    ],
  },
  {
    to: '/changes',
    label: 'Changes',
    icon: FileDiff,
    scope: 'knowledge:read',
    group: 'wiki',
    api: [
      '/v1/spaces/{space}/proposals',
      '/v1/proposals/{id}',
      '/v1/proposals/{id}/lint',
      '/v1/proposals/{id}/approve',
      '/v1/proposals/{id}/reject',
      '/v1/proposals/{id}/request-changes',
      '/v1/proposals/{id}/split',
    ],
  },
  {
    to: '/sources',
    label: 'Sources',
    icon: Archive,
    scope: 'knowledge:read',
    group: 'wiki',
    // The two ingest paths are here because the archive is where a document
    // ENTERS: the page starts the ingest and then polls the job it created.
    api: [
      '/v1/spaces/{space}/sources',
      '/v1/spaces/{space}/sources/{id}',
      '/v1/spaces/{space}/source-streams',
      '/v1/spaces/{space}/source-streams/{external_source_id}',
      '/v1/spaces/{space}/ingest',
      '/v1/ingests/{id}',
    ],
  },
  {
    to: '/decisions',
    label: 'Decisions',
    icon: Scale,
    scope: 'knowledge:read',
    group: 'wiki',
    api: ['/v1/spaces/{space}/decisions', '/v1/spaces/{space}/decisions/{slug}'],
  },
  {
    to: '/search',
    label: 'Search',
    icon: Search,
    scope: 'knowledge:read',
    group: 'wiki',
    api: ['/v1/spaces/{space}/search', '/v1/spaces/{space}/query'],
  },
  {
    to: '/charter',
    label: 'Charter',
    icon: ScrollText,
    scope: 'knowledge:read',
    group: 'wiki',
    api: ['/v1/spaces/{space}/charter', '/v1/spaces/{space}/charter/versions'],
  },
  {
    to: '/spaces',
    label: 'Wikis',
    icon: FolderKanban,
    scope: 'knowledge:read',
    group: 'installation',
    api: ['/v1/spaces', '/v1/spaces/{space}', '/v1/spaces/{space}/settings', '/v1/spaces/{space}/export'],
  },
  {
    to: '/api-keys',
    label: 'API keys',
    icon: KeyRound,
    scope: 'admin',
    group: 'installation',
    api: ['/v1/api-keys', '/v1/api-keys/{id}'],
  },
  {
    to: '/identities',
    label: 'People',
    icon: Users,
    scope: 'admin',
    group: 'installation',
    api: ['/v1/identities', '/v1/identities/{provider}/{subject}'],
  },
  {
    to: '/webhooks',
    label: 'Webhooks',
    icon: Webhook,
    scope: 'admin',
    group: 'installation',
    api: ['/v1/spaces/{space}/webhooks', '/v1/spaces/{space}/webhooks/{id}/deliveries'],
  },
  {
    to: '/system',
    label: 'System',
    icon: Server,
    scope: 'knowledge:read',
    group: 'installation',
    // The admin-only cards on this page render the server's own 403 rather
    // than disappearing — a reader should be able to see that the numbers
    // exist and are not theirs, which is a different fact from "no data".
    //
    // The first two paths are the surprising ones: `/ready` and the service
    // descriptor are unauthenticated and outside /v1, so this page can show
    // what the installation IS and whether it is up before it shows a single
    // number a scope could withhold.
    api: [
      '/ready',
      '/.well-known/service-descriptor.json',
      '/v1/spaces/{space}/lint',
      '/v1/spaces/{space}/stats/http',
      '/v1/spaces/{space}/stats/usage',
      '/v1/spaces/{space}/stats/llm',
      '/v1/spaces/{space}/stats/webhooks',
      '/v1/stats/mcp',
      '/v1/installation/knowledge-config',
    ],
  },
]

export interface NavGroup {
  id: string
  label: string
  collapsible: boolean
  startsOpen: boolean
  separated: boolean
}

/**
 * The groups, in the order an operator meets them.
 *
 * Three, not five. The console is a wiki: there is the page you are on, the
 * wiki you are in, and — folded away — the installation that hosts it. Every
 * extra top-level heading is one more decision before the reader gets to read
 * anything, and a knowledge base whose navigation needs studying is a knowledge
 * base nobody browses.
 *
 * Installation is separated because it is the only block about WikiKit itself
 * rather than about the knowledge it holds.
 */
export const GROUPS: readonly NavGroup[] = [
  { id: 'home', label: '', collapsible: false, startsOpen: true, separated: false },
  { id: 'wiki', label: 'Wiki', collapsible: true, startsOpen: true, separated: false },
  { id: 'installation', label: 'Installation', collapsible: true, startsOpen: false, separated: true },
]

/** The nav entry a path belongs to — the longest matching prefix. */
export function entryFor(path: string): NavEntry | undefined {
  let best: NavEntry | undefined
  for (const entry of NAV) {
    const matches = entry.exact ? path === entry.to : path === entry.to || path.startsWith(`${entry.to}/`)
    if (matches && (!best || entry.to.length > best.to.length)) best = entry
  }
  return best
}
