// Generates src/cockpit-embedded.ts from the built console in assets/cockpit.
//
// WHY this exists at all: `bun build --compile` produces one file, and a
// readFileSync against assets/cockpit inside it resolves to a path that does
// not exist on the operator's machine. The promise is a SINGLE artifact — one
// download, no unpack step, no sidecar directory — so the console has to travel
// inside it the same way the migrations and the documentation already do.
//
// Same shape as gen-embedded-migrations.ts on purpose: generate, commit, and
// let a drift test fail the build when the generated file no longer matches
// what is on disk. A generated artifact that is not drift-checked is a
// generated artifact that is stale.
//
//   bun run gen:cockpit            regenerate
//   bun run check:cockpit-drift    fail if it is stale
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const BUNDLE_DIR = join(root, 'assets', 'cockpit')
const OUTPUT = join(root, 'src', 'cockpit-embedded.ts')

function walk(dir: string, found: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) walk(full, found)
    else found.push(full)
  }
  return found
}

function generate(): string {
  let files: string[] = []
  try {
    files = walk(BUNDLE_DIR).sort()
  } catch {
    // No bundle built. The module still has to exist and typecheck — a
    // checkout that has never run the console build must not fail to compile.
  }

  const entries = files.map((file) => {
    // POSIX separators: the key is a URL path, and a Windows build must not
    // emit backslashes that no request will ever match.
    const key = relative(BUNDLE_DIR, file).split(sep).join('/')
    return `  '${key}': '${readFileSync(file).toString('base64')}',`
  })

  return `// GENERATED by scripts/gen-embedded-cockpit.ts — do not edit.
//
// The built cockpit, base64-encoded so it travels inside a compiled binary.
// Regenerate with \`bun run gen:cockpit\`; a drift check compares this against
// assets/cockpit and fails the gate when they disagree.
//
// Base64 rather than a raw string because the bundle contains binary assets
// (fonts, images) as well as text, and one encoding for all of them is one
// decode path rather than two.
export const EMBEDDED_COCKPIT: Record<string, string> = {
${entries.join('\n')}
}

/** How many files the bundle contains. Zero means it was never built. */
export const EMBEDDED_COCKPIT_FILES = ${files.length}
`
}

const generated = generate()
const check = process.argv.includes('--check')

if (check) {
  let current = ''
  try {
    current = readFileSync(OUTPUT, 'utf8')
  } catch {
    current = ''
  }
  if (current !== generated) {
    console.error('src/cockpit-embedded.ts is stale — run `bun run build:cockpit`')
    process.exit(1)
  }
  console.log('cockpit bundle embedding is current')
} else {
  writeFileSync(OUTPUT, generated)
  console.log(`wrote src/cockpit-embedded.ts (${(generated.length / 1024).toFixed(0)} kB)`)
}
