#!/usr/bin/env bun
// Regenerates src/db/migrations/embedded.ts from the SQL files + journal.
//
// WHY embedding: the compiled single binary (`bun build --compile`) must not
// read migration files from disk at runtime — SQL and journal become literal
// module values. The generated file is committed and drift-tested against the
// .sql sources (test/unit/embedded-drift.test.ts), so an edited migration
// without a re-run of this script fails CI instead of silently shipping a
// stale bundle.
import { spawnSync } from 'node:child_process'
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const migrationsDir = join(root, 'src', 'db', 'migrations')
const journalPath = join(migrationsDir, 'meta', '_journal.json')
const outputPath = join(migrationsDir, 'embedded.ts')

interface JournalEntry {
  idx: number
  tag: string
  when: number
  breakpoints: boolean
}
interface Journal {
  version: string
  dialect: string
  entries: JournalEntry[]
}

const journal = JSON.parse(await readFile(journalPath, 'utf8')) as Journal
const entries = [...journal.entries].sort((a, b) => a.idx - b.idx)
const sqlByTag: Record<string, string> = {}
for (const entry of entries) {
  sqlByTag[entry.tag] = await readFile(join(migrationsDir, `${entry.tag}.sql`), 'utf8')
}

const output = `// Build-time embedded migration bundle.
//
// AUTO-GENERATED by scripts/gen-embedded-migrations.ts. Do not edit.
// SQL and journal data are literal module values, so the runtime reads no
// migration files after the single WikiKit binary has been built.
import { createHash } from 'node:crypto'

export interface EmbeddedJournalEntry {
  idx: number
  tag: string
  when: number
  breakpoints: boolean
}

export interface EmbeddedMigration {
  idx: number
  tag: string
  when: number
  /** Full migration file content — the drift/hash anchor. */
  sql: string
  /** sha256 hex of \`sql\`; recorded in wk_migrations for drift detection. */
  hash: string
  /** \`sql\` split on '--> statement-breakpoint' markers (whole file when none). */
  statements: string[]
}

export const EMBEDDED_JOURNAL: { version: string; dialect: string; entries: EmbeddedJournalEntry[] } =
  ${JSON.stringify(journal, null, 2).split('\n').join('\n  ')}

const SQL_BY_TAG: Record<string, string> = ${JSON.stringify(sqlByTag, null, 2)}

export const EMBEDDED_MIGRATIONS: EmbeddedMigration[] = EMBEDDED_JOURNAL.entries
  .slice()
  .sort((a, b) => a.idx - b.idx)
  .map((entry) => {
    const sql = SQL_BY_TAG[entry.tag]
    if (sql === undefined) throw new Error(\`embedded migration missing SQL for \${entry.tag}\`)
    const statements = sql
      .split('--> statement-breakpoint')
      .map((value) => value.trim())
      .filter(Boolean)
    return {
      idx: entry.idx,
      tag: entry.tag,
      when: entry.when,
      sql,
      hash: createHash('sha256').update(sql).digest('hex'),
      statements,
    }
  })
`
await writeFile(outputPath, output, 'utf8')
// The generated file is committed and lint-checked like hand-written code, so
// it must be prettier-stable: format it here instead of teaching the template
// every style rule.
spawnSync('bunx', ['prettier', '--write', outputPath], { cwd: root, stdio: 'ignore' })
process.stdout.write(`wrote ${relative(root, outputPath)} (${entries.length} migrations)\n`)
