// Document extraction over REAL binary fixtures (generated by
// scripts/gen-doc-fixtures.ts). Proves pdf/docx/xlsx text survives extraction,
// text formats pass through, and the error paths (415/422) fire.
import { describe, expect, test } from 'bun:test'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { extractDocument, UnsupportedDocumentError, DocumentExtractionError } from '../../src/ingest/extract.ts'

const DIR = join(import.meta.dir, '../fixtures/documents')
const bytes = (name: string) => new Uint8Array(readFileSync(join(DIR, name)))

describe('extractDocument', () => {
  test('pdf → text layer extracted', async () => {
    const r = await extractDocument(bytes('sample.pdf'), 'sample.pdf')
    expect(r.format).toBe('pdf')
    expect(r.title).toBe('sample')
    expect(r.markdown).toContain('Open Knowledge Format')
    expect(r.markdown).toContain('concept identity')
  })

  test('docx → markdown', async () => {
    const r = await extractDocument(bytes('sample.docx'), 'report.docx')
    expect(r.format).toBe('docx')
    expect(r.title).toBe('report')
    // mammoth escapes markdown punctuation; assert on the words, not exact bytes.
    expect(r.markdown.replace(/\\/g, '')).toContain('The Open Knowledge Format is a draft v0.1.')
    expect(r.markdown).toContain('# Open Knowledge Format') // heading preserved
  })

  test('xlsx → markdown tables (sheet name + cells)', async () => {
    const r = await extractDocument(bytes('sample.xlsx'), 'prices.xlsx')
    expect(r.format).toBe('xlsx')
    expect(r.markdown).toContain('## Prices')
    expect(r.markdown).toContain('| Product | Price |')
    expect(r.markdown).toContain('| Reifen A | 120 |')
  })

  test('md / txt / csv pass through verbatim as text', async () => {
    const md = await extractDocument(new Uint8Array(Buffer.from('# Title\n\nBody.')), 'a.md')
    expect(md.format).toBe('markdown')
    expect(md.markdown).toBe('# Title\n\nBody.')

    const csv = await extractDocument(new Uint8Array(Buffer.from('a,b\n1,2')), 'data.csv')
    expect(csv.format).toBe('csv')
    expect(csv.markdown).toBe('a,b\n1,2')
  })

  test('unknown extension → UnsupportedDocumentError (415)', async () => {
    await expect(extractDocument(new Uint8Array([1, 2, 3]), 'archive.zip')).rejects.toBeInstanceOf(
      UnsupportedDocumentError,
    )
    await expect(extractDocument(new Uint8Array([1]), 'noext')).rejects.toMatchObject({ statusCode: 415 })
  })

  test('empty text document → DocumentExtractionError (422)', async () => {
    await expect(extractDocument(new Uint8Array(Buffer.from('   \n  ')), 'blank.txt')).rejects.toBeInstanceOf(
      DocumentExtractionError,
    )
  })

  test('corrupt binary for a real format → DocumentExtractionError (422), not a crash', async () => {
    await expect(extractDocument(new Uint8Array(Buffer.from('not a real pdf')), 'broken.pdf')).rejects.toMatchObject({
      statusCode: 422,
    })
  })
})
